name: Build DS18b20 Custom Chip

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build chip
      uses: bonnyr/wokwi-chip-clang-action@main
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: chip
        path: |
          dist/chip.tar.gz
          dist/chip.json
          dist/chip.wasm

